create sequence id_seq start with 1 increment by 1 no maxvalue
drop table tb_alink
create table tb_alink
(
id int GENERATED BY DEFAULT AS SEQUENCE id_seq primary key,
url varchar(255) default null,
ssl int default 0,
remark varchar(255) default null,
input_date TIMESTAMP default sysdate,
input_user varchar(20) default null,
update_date TIMESTAMP default null,
update_user varchar(20) default null
)


insert into tb_alink(use,url) values ('N','http://bbs.pchome.net/');

update tb_alink set use = 'N' where id = 1;

select ta.url from tb_alink ta where ta.url like '%user%';

update tb_email set send_date = null, send_status = null, msg_id = null where id in (3,5,6,7,8);